/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tr_ast_pbo.admin;

import java.awt.Color;
import javax.swing.JFrame;
import com.mycompany.tr_ast_pbo.DarkMode;

/**
 *
 * @author Made
 */
public class adminPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminPage.class.getName());

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Setup dark mode toggle listeners
        darkModeToggle.addActionListener(evt -> darkModeToggleActionPerformed(evt));
        darkModeToggle1.addActionListener(evt -> jToggleButton2ActionPerformed(evt));
        
        setDarkMode(DarkMode.isDarkMode);
    }
    
    private void setDarkMode(boolean isDark) {
        if(isDark){
            jPanel1.setBackground(new Color(44, 44, 44));
            mainPanel.setBackground(new Color(44, 44, 44));
            jPanel2.setBackground(new Color(44, 44, 44));
            panelEditAnggota.setBackground(new Color(44, 44, 44));
            panelEditBuku.setBackground(new Color(44, 44, 44));
            tablePanel.setBackground(new Color(44, 44, 44));
            tabPanel.setBackground(new Color(44, 44, 44));
            perpus.setForeground(Color.WHITE);
            judulMenuAnggota.setForeground(Color.WHITE);
            judulMenuBuku.setForeground(Color.WHITE);
            namaAnggota.setForeground(Color.WHITE);
            password.setForeground(Color.WHITE);
            namaBuku.setForeground(Color.WHITE);
            penulis.setForeground(Color.WHITE);
            stok.setForeground(Color.WHITE);
            tglTerbit.setForeground(Color.WHITE);
        }else{
            jPanel1.setBackground(new Color(249, 248, 246));
            mainPanel.setBackground(new Color(249, 248, 246));
            jPanel2.setBackground(new Color(249, 248, 246));
            panelEditAnggota.setBackground(new Color(249, 248, 246));
            panelEditBuku.setBackground(new Color(249, 248, 246));
            tablePanel.setBackground(new Color(249, 248, 246));
            tabPanel.setBackground(new Color(249, 248, 246));
            perpus.setForeground(Color.BLACK);
            judulMenuAnggota.setForeground(Color.BLACK);
            judulMenuBuku.setForeground(Color.BLACK);
            namaAnggota.setForeground(Color.BLACK);
            password.setForeground(Color.BLACK);
            namaBuku.setForeground(Color.BLACK);
            penulis.setForeground(Color.BLACK);
            stok.setForeground(Color.BLACK);
            tglTerbit.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perpus = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelEditAnggota = new javax.swing.JPanel();
        judulMenuAnggota = new javax.swing.JLabel();
        namaAnggota = new javax.swing.JLabel();
        namaAnggotaInput = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        tambahBtn1 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        cancelBtn1 = new javax.swing.JButton();
        darkModeToggle1 = new javax.swing.JToggleButton();
        panelEditBuku = new javax.swing.JPanel();
        judulMenuBuku = new javax.swing.JLabel();
        namaBuku = new javax.swing.JLabel();
        namaBukuInput = new javax.swing.JTextField();
        penulis = new javax.swing.JLabel();
        penulisInput = new javax.swing.JTextField();
        stok = new javax.swing.JLabel();
        stokInput = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        tglTerbit = new javax.swing.JLabel();
        tglTerbitInput = new javax.swing.JTextField();
        darkModeToggle = new javax.swing.JToggleButton();
        tablePanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnggota = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(3000, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1617, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        perpus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        perpus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perpus.setText("PERPUSTAKAAN");
        jPanel1.add(perpus);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 539));
        jPanel2.setLayout(new java.awt.CardLayout());

        panelEditAnggota.setPreferredSize(new java.awt.Dimension(400, 300));

        judulMenuAnggota.setText("MENU EDIT ANGGOTA");

        namaAnggota.setText("Nama Anggota :");

        password.setText("Password :");

        tambahBtn1.setText("Tambah");
        tambahBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn1ActionPerformed(evt);
            }
        });

        editBtn1.setText("Edit");
        editBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn1ActionPerformed(evt);
            }
        });

        deleteBtn1.setText("Delete");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        cancelBtn1.setText("Cancel");
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });

        darkModeToggle1.setText("Dark Mode");

        javax.swing.GroupLayout panelEditAnggotaLayout = new javax.swing.GroupLayout(panelEditAnggota);
        panelEditAnggota.setLayout(panelEditAnggotaLayout);
        panelEditAnggotaLayout.setHorizontalGroup(
            panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(judulMenuAnggota))
                    .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaAnggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaAnggotaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(passwordInput)))
                    .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(darkModeToggle1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                                .addComponent(tambahBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelEditAnggotaLayout.setVerticalGroup(
            panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulMenuAnggota)
                .addGap(18, 18, 18)
                .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaAnggota)
                    .addComponent(namaAnggotaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panelEditAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn1)
                    .addComponent(editBtn1)
                    .addComponent(deleteBtn1)
                    .addComponent(cancelBtn1))
                .addGap(49, 49, 49)
                .addComponent(darkModeToggle1)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jPanel2.add(panelEditAnggota, "cardAnggota");

        panelEditBuku.setPreferredSize(new java.awt.Dimension(400, 300));

        judulMenuBuku.setText("MENU EDIT BUKU");

        namaBuku.setText("Nama Buku: ");

        penulis.setText("Penulis :");

        stok.setText("Stok :");

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        tglTerbit.setText("Tgl Terbit :");

        darkModeToggle.setText("Dark Mode");

        javax.swing.GroupLayout panelEditBukuLayout = new javax.swing.GroupLayout(panelEditBuku);
        panelEditBuku.setLayout(panelEditBukuLayout);
        panelEditBukuLayout.setHorizontalGroup(
            panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditBukuLayout.createSequentialGroup()
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEditBukuLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(judulMenuBuku))
                    .addGroup(panelEditBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(penulis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaBukuInput)
                            .addComponent(penulisInput)
                            .addComponent(stokInput, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                    .addGroup(panelEditBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tglTerbit)
                        .addGap(18, 18, 18)
                        .addComponent(tglTerbitInput, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditBukuLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(darkModeToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEditBukuLayout.createSequentialGroup()
                        .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        panelEditBukuLayout.setVerticalGroup(
            panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulMenuBuku)
                .addGap(18, 18, 18)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBuku)
                    .addComponent(namaBukuInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penulis)
                    .addComponent(penulisInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok)
                    .addComponent(stokInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglTerbit)
                    .addComponent(tglTerbitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelEditBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(cancelBtn))
                .addGap(49, 49, 49)
                .addComponent(darkModeToggle)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanel2.add(panelEditBuku, "cardBuku");

        mainPanel.add(jPanel2, java.awt.BorderLayout.WEST);

        tablePanel.setPreferredSize(new java.awt.Dimension(700, 768));
        tablePanel.setLayout(new java.awt.BorderLayout());

        tableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAnggota.setShowGrid(true);
        jScrollPane1.setViewportView(tableAnggota);

        tabPanel.addTab("Anggota", jScrollPane1);

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.setShowGrid(true);
        jScrollPane2.setViewportView(tableBuku);

        tabPanel.addTab("Buku", jScrollPane2);

        tablePanel.add(tabPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(tablePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void tambahBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBtn1ActionPerformed

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtn1ActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void darkModeToggleActionPerformed(java.awt.event.ActionEvent evt) {
        setDarkMode(darkModeToggle.isSelected());
        DarkMode.isDarkMode = darkModeToggle.isSelected();
        
        if (darkModeToggle.isSelected()) {
            darkModeToggle.setText("Light Mode");
            darkModeToggle1.setSelected(true);
            darkModeToggle1.setText("Light Mode");
        } else {
            darkModeToggle.setText("Dark Mode");
            darkModeToggle1.setSelected(false);
            darkModeToggle1.setText("Dark Mode");
        }
    }

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        setDarkMode(darkModeToggle1.isSelected());
        DarkMode.isDarkMode = darkModeToggle1.isSelected();
        
        if (darkModeToggle1.isSelected()) {
            darkModeToggle1.setText("Light Mode");
            darkModeToggle.setSelected(true);
            darkModeToggle.setText("Light Mode");
        } else {
            darkModeToggle1.setText("Dark Mode");
            darkModeToggle.setSelected(false);
            darkModeToggle.setText("Dark Mode");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JToggleButton darkModeToggle;
    private javax.swing.JToggleButton darkModeToggle1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulMenuAnggota;
    private javax.swing.JLabel judulMenuBuku;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaAnggota;
    private javax.swing.JTextField namaAnggotaInput;
    private javax.swing.JLabel namaBuku;
    private javax.swing.JTextField namaBukuInput;
    private javax.swing.JPanel panelEditAnggota;
    private javax.swing.JPanel panelEditBuku;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel penulis;
    private javax.swing.JTextField penulisInput;
    private javax.swing.JLabel perpus;
    private javax.swing.JLabel stok;
    private javax.swing.JTextField stokInput;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tableAnggota;
    private javax.swing.JTable tableBuku;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton tambahBtn1;
    private javax.swing.JLabel tglTerbit;
    private javax.swing.JTextField tglTerbitInput;
    // End of variables declaration//GEN-END:variables
}
