/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tr_ast_pbo.user;

import com.mycompany.tr_ast_pbo.loginPage;
import com.mycompany.tr_ast_pbo.DarkMode;
import DTO.PinjamDTO;
import objek.Buku;
import repo.BukuRepository;
import repo.PinjamRepository;

import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Windows
 */
public class PeminjamanUser extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PeminjamanUser.class.getName());
    private String currentUser;
    private PinjamRepository pinjamRepo = new PinjamRepository();
    private BukuRepository bukuRepo = new BukuRepository();

    public PeminjamanUser(String userId) {
        this.currentUser = userId;
        initComponents();

        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

        loadPeminjamanSaya();
        setDarkMode(DarkMode.isDarkMode);
    }

    public PeminjamanUser() {
        this("GUEST");
    }

    private void loadPeminjamanSaya() {
        jPanel3.removeAll();
        List<PinjamDTO> listPinjam = pinjamRepo.getPinjamByAnggota(currentUser);

        for(PinjamDTO data : listPinjam) {
            JPanel item = createLoanItem(data);
            jPanel3.add(item);
            jPanel3.add(Box.createVerticalStrut(15));
        }

        jPanel3.revalidate();
        jPanel3.repaint();
    }

    private JPanel createLoanItem(PinjamDTO data) {
        JPanel panel = new JPanel();
        panel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        panel.setMaximumSize(new Dimension(800, 100));
        panel.setLayout(new BorderLayout());

        JPanel leftPanel = new JPanel();
        leftPanel.setOpaque(false);
        leftPanel.setLayout(new GridLayout(4, 1));

        leftPanel.add(new JLabel("Judul: " + data.getNama_buku())); // Dari DTO JOIN
        leftPanel.add(new JLabel("ID Buku: " + data.getId_buku()));
        leftPanel.add(new JLabel("Tgl Pinjam: " + data.getTanggal_pinjam()));
        JLabel lblDeadline = new JLabel("Deadline: " + data.getDeadline());
        lblDeadline.setForeground(Color.RED);
        leftPanel.add(lblDeadline);

        JPanel rightPanel = new JPanel();
        rightPanel.setOpaque(false);
        rightPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

        JButton btnPerpanjang = new JButton("Perpanjang");
        btnPerpanjang.setBackground(Color.LIGHT_GRAY);

        JButton btnKembali = new JButton("Kembalikan");
        btnKembali.setBackground(new Color(102, 255, 0));

        btnKembali.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(this, "Kembalikan buku " + data.getNama_buku() + "?");
            if(confirm == JOptionPane.YES_OPTION) {
                boolean success = pinjamRepo.returnBuku(data.getId_pinjam());

                if(success) {
                    Buku b = bukuRepo.getBukuById(data.getId_buku());
                    if(b != null) {
                        bukuRepo.changeStock(data.getId_buku(), b.getStok() + 1);
                    }

                    JOptionPane.showMessageDialog(this, "Buku dikembalikan!");
                    jPanel3.remove(panel);
                    jPanel3.revalidate();
                    jPanel3.repaint();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengembalikan buku.");
                }
            }
        });

        rightPanel.add(btnPerpanjang);
        rightPanel.add(btnKembali);
        panel.add(leftPanel, BorderLayout.CENTER);
        panel.add(rightPanel, BorderLayout.EAST);

        return panel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Perpanjang = new javax.swing.JButton();
        Kembalikan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Perpanjang1 = new javax.swing.JButton();
        Kembalikan1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Perpanjang2 = new javax.swing.JButton();
        Kembalikan2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        tambahBtn6 = new javax.swing.JButton();
        editBtn9 = new javax.swing.JButton();
        editBtn10 = new javax.swing.JButton();
        editBtn11 = new javax.swing.JButton();
        tambahBtn7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label2.setText("Peminjaman Saya");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Judul Buku");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Penulis");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        jLabel3.setText("waktu dipinjam");

        jLabel4.setText("Deadline peminjaman");

        Perpanjang.setBackground(new java.awt.Color(204, 204, 204));
        Perpanjang.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Perpanjang.setText("Perpanjang");

        Kembalikan.setBackground(new java.awt.Color(102, 255, 0));
        Kembalikan.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Kembalikan.setText("Kembalikan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 658, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Perpanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kembalikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Perpanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setText("Judul Buku");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Penulis");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        jLabel7.setText("waktu dipinjam");

        jLabel8.setText("Deadline peminjaman");

        Perpanjang1.setBackground(new java.awt.Color(204, 204, 204));
        Perpanjang1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Perpanjang1.setText("Perpanjang");

        Kembalikan1.setBackground(new java.awt.Color(102, 255, 0));
        Kembalikan1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Kembalikan1.setText("Kembalikan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Perpanjang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kembalikan1))
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Perpanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kembalikan1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setText("Judul Buku");

        jLabel10.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel10.setText("Penulis");

        jLabel11.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        jLabel11.setText("waktu dipinjam");

        jLabel12.setText("Deadline peminjaman");

        Perpanjang2.setBackground(new java.awt.Color(204, 204, 204));
        Perpanjang2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Perpanjang2.setText("Perpanjang");

        Kembalikan2.setBackground(new java.awt.Color(102, 255, 0));
        Kembalikan2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Kembalikan2.setText("Kembalikan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Perpanjang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kembalikan2))
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Perpanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kembalikan2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(102, 102, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label5.setText("Perpustakaan Digital");

        tambahBtn6.setBackground(new java.awt.Color(153, 153, 255));
        tambahBtn6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tambahBtn6.setText("Home");
        tambahBtn6.setName(""); // NOI18N
        tambahBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn6HomeBtnActionPerformed(evt);
            }
        });

        editBtn9.setBackground(new java.awt.Color(153, 153, 255));
        editBtn9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        editBtn9.setText("Katalog");
        editBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn9KatalogBtnActionPerformed(evt);
            }
        });

        editBtn10.setBackground(new java.awt.Color(153, 153, 255));
        editBtn10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        editBtn10.setText("Peminjaman");
        editBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn10ActionPerformed(evt);
            }
        });

        editBtn11.setBackground(new java.awt.Color(153, 153, 255));
        editBtn11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        editBtn11.setText("Dark Mode");
        editBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn11ActionPerformed(evt);
            }
        });

        tambahBtn7.setBackground(new java.awt.Color(153, 153, 255));
        tambahBtn7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tambahBtn7.setText("Logout");
        tambahBtn7.setName(""); // NOI18N
        tambahBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn7LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn9)
                .addGap(18, 18, 18)
                .addComponent(editBtn10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tambahBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tambahBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBtn6HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn6HomeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DashboardUser(currentUser).setVisible(true);
    }//GEN-LAST:event_tambahBtn6HomeBtnActionPerformed

    private void editBtn9KatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn9KatalogBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new KatalogUser(currentUser).setVisible(true);
    }//GEN-LAST:event_editBtn9KatalogBtnActionPerformed

    private void editBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtn10ActionPerformed

    private void editBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn11ActionPerformed
        DarkMode.isDarkMode = !DarkMode.isDarkMode;
        setDarkMode(DarkMode.isDarkMode);
    }//GEN-LAST:event_editBtn11ActionPerformed

    private void tambahBtn7LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn7LogoutBtnActionPerformed
        this.dispose();
        new loginPage().setVisible(true);
    }//GEN-LAST:event_tambahBtn7LogoutBtnActionPerformed

    private void setDarkMode(boolean isDark) {
        if (isDark) {
            // Dark mode colors
            Color darkBg = new Color(44, 44, 44);
            Color darkPanel = new Color(60, 60, 60);
            Color darkText = Color.WHITE;
            Color darkButton = new Color(70, 70, 70);
            
            // Main panels
            jPanel12.setBackground(new Color(30, 30, 30));
            jPanel2.setBackground(darkBg);
            jPanel3.setBackground(darkBg);
            
            // Book panels
            jPanel4.setBackground(darkPanel);
            jPanel5.setBackground(darkPanel);
            jPanel6.setBackground(darkPanel);
            
            // Labels
            label2.setForeground(darkText);
            label5.setForeground(darkText);
            jLabel1.setForeground(darkText);
            jLabel2.setForeground(darkText);
            jLabel3.setForeground(darkText);
            jLabel4.setForeground(darkText);
            jLabel5.setForeground(darkText);
            jLabel6.setForeground(darkText);
            jLabel7.setForeground(darkText);
            jLabel8.setForeground(darkText);
            jLabel9.setForeground(darkText);
            jLabel10.setForeground(darkText);
            jLabel11.setForeground(darkText);
            jLabel12.setForeground(darkText);
            
            // Buttons
            tambahBtn6.setBackground(darkButton);
            tambahBtn6.setForeground(darkText);
            editBtn9.setBackground(darkButton);
            editBtn9.setForeground(darkText);
            editBtn10.setBackground(darkButton);
            editBtn10.setForeground(darkText);
            editBtn11.setBackground(darkButton);
            editBtn11.setForeground(darkText);
            editBtn11.setText("Light Mode");
            tambahBtn7.setBackground(darkButton);
            tambahBtn7.setForeground(darkText);
            
            // Action buttons
            Perpanjang.setBackground(darkButton);
            Perpanjang.setForeground(darkText);
            Kembalikan.setForeground(Color.BLACK);
            Perpanjang1.setBackground(darkButton);
            Perpanjang1.setForeground(darkText);
            Kembalikan1.setForeground(Color.BLACK);
            Perpanjang2.setBackground(darkButton);
            Perpanjang2.setForeground(darkText);
            Kembalikan2.setForeground(Color.BLACK);
            
        } else {
            // Light mode colors
            Color lightBg = Color.WHITE;
            Color lightPanel = Color.WHITE;
            Color lightText = Color.BLACK;
            
            // Main panels
            jPanel12.setBackground(new Color(102, 102, 255));
            jPanel2.setBackground(lightBg);
            jPanel3.setBackground(lightBg);
            
            // Book panels
            jPanel4.setBackground(lightPanel);
            jPanel5.setBackground(lightPanel);
            jPanel6.setBackground(lightPanel);
            
            // Labels
            label2.setForeground(lightText);
            label5.setForeground(lightText);
            jLabel1.setForeground(lightText);
            jLabel2.setForeground(lightText);
            jLabel3.setForeground(lightText);
            jLabel4.setForeground(lightText);
            jLabel5.setForeground(lightText);
            jLabel6.setForeground(lightText);
            jLabel7.setForeground(lightText);
            jLabel8.setForeground(lightText);
            jLabel9.setForeground(lightText);
            jLabel10.setForeground(lightText);
            jLabel11.setForeground(lightText);
            jLabel12.setForeground(lightText);
            
            // Buttons
            tambahBtn6.setBackground(new Color(153, 153, 255));
            tambahBtn6.setForeground(lightText);
            editBtn9.setBackground(new Color(153, 153, 255));
            editBtn9.setForeground(lightText);
            editBtn10.setBackground(new Color(153, 153, 255));
            editBtn10.setForeground(lightText);
            editBtn11.setBackground(new Color(153, 153, 255));
            editBtn11.setForeground(lightText);
            editBtn11.setText("Dark Mode");
            tambahBtn7.setBackground(new Color(153, 153, 255));
            tambahBtn7.setForeground(lightText);
            
            // Action buttons
            Perpanjang.setBackground(new Color(204, 204, 204));
            Perpanjang.setForeground(lightText);
            Kembalikan.setForeground(Color.BLACK);
            Perpanjang1.setBackground(new Color(204, 204, 204));
            Perpanjang1.setForeground(lightText);
            Kembalikan1.setForeground(Color.BLACK);
            Perpanjang2.setBackground(new Color(204, 204, 204));
            Perpanjang2.setForeground(lightText);
            Kembalikan2.setForeground(Color.BLACK);
        }
        
        // Repaint to apply changes
        this.repaint();
    }

    private void updateRecursiveColor(Container container, Color bg, Color text) {
        for(Component c : container.getComponents()) {
            if(c instanceof JLabel) {
                ((JLabel)c).setForeground(text);
            }
            if(c instanceof JPanel) {
                c.setBackground(bg);
                updateRecursiveColor((Container)c, bg, text);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PeminjamanUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembalikan;
    private javax.swing.JButton Kembalikan1;
    private javax.swing.JButton Kembalikan2;
    private javax.swing.JButton Perpanjang;
    private javax.swing.JButton Perpanjang1;
    private javax.swing.JButton Perpanjang2;
    private javax.swing.JButton editBtn10;
    private javax.swing.JButton editBtn11;
    private javax.swing.JButton editBtn6;
    private javax.swing.JButton editBtn7;
    private javax.swing.JButton editBtn8;
    private javax.swing.JButton editBtn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JButton tambahBtn4;
    private javax.swing.JButton tambahBtn5;
    private javax.swing.JButton tambahBtn6;
    private javax.swing.JButton tambahBtn7;
    // End of variables declaration//GEN-END:variables
}